#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures for ContentJSON (content ref 2).
//
// Yjs no longer creates ContentJSON from its public API, but still decodes it
// and old documents still carry it. Its wire form is NOT lib0 Any in either
// version: ContentJSON.write does writeLen(n) then writeString(JSON.stringify(c))
// per value ('undefined' for undefined), and readContentJSON reverses that. The
// items are therefore built directly with new Y.Item(..., new Y.ContentJSON()).
//
// Rows with exact=true use values whose JSON text Go reproduces byte-for-byte
// (no undefined, no multi-key objects, no U+2028), so ygo's re-encode must
// equal yjs's bytes.
// diffClock rows also carry yjs's diff from state vector {7: diffClock}, which
// splits the ContentJSON item and exercises the encoder's offset path.
//
// Regenerated by `make fixtures`; CI's drift gate diffs the result.
const Y = require('yjs')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')
const CLIENT = 7

// insertJSON integrates a ContentJSON item at the end of parent (or under key).
function insertJSON (doc, parent, vals, key = null) {
	doc.transact((tr) => {
		const left = key === null ? parent._start && lastItem(parent) : parent._map.get(key) || null
		const it = new Y.Item(
			Y.createID(CLIENT, Y.getState(doc.store, CLIENT)),
			left, left && left.lastId, null, null, parent, key, new Y.ContentJSON(vals))
		it.integrate(tr, 0)
	})
}

function lastItem (parent) {
	let n = parent._start
	while (n.right !== null) n = n.right
	return n
}

function one (name, kind, exact, build, diffClock) {
	const d = new Y.Doc()
	d.clientID = CLIENT
	build(d)
	const t = { map: d.getMap('m'), array: d.getArray('a'), xml: d.getXmlFragment('x') }[kind]
	const row = {
		name,
		kind,
		exact,
		v1: hex(Y.encodeStateAsUpdate(d)),
		v2: hex(Y.encodeStateAsUpdateV2(d)),
		expected: t.toJSON(),
	}
	if (diffClock !== undefined) {
		const sv = Y.encodeStateVector(new Map([[CLIENT, diffClock]]))
		row.diffClock = diffClock
		row.v1Diff = hex(Y.encodeStateAsUpdate(d, sv))
		row.v2Diff = hex(Y.encodeStateAsUpdateV2(d, sv))
	}
	return row
}

const rows = [
	one('array_scalars', 'array', true, (d) => {
		insertJSON(d, d.getArray('a'), [1, -3, 1.5, 1e21, 1e-7, 2 ** 53 + 2, 'two', '', 'héllo 😀', '<&>"\\', true, false, null])
	}),
	one('array_nested', 'array', true, (d) => {
		insertJSON(d, d.getArray('a'), [{ k: [1, null, true, { x: 'y' }] }, [], {}, [[], [1, ['deep']]]])
	}),
	one('array_undefined_only', 'array', false, (d) => {
		insertJSON(d, d.getArray('a'), [undefined, undefined])
	}),
	// Neighbouring Any items prove the decoder consumed exactly the JSON
	// strings: a misread length desynchronises every later struct.
	one('array_between_any_items', 'array', true, (d) => {
		const a = d.getArray('a')
		a.push(['before'])
		insertJSON(d, a, ['j0', 2, null])
		a.push(['after', 3])
	}),
	one('array_split_by_diff', 'array', true, (d) => {
		insertJSON(d, d.getArray('a'), ['s0', 1, { k: 'v' }, null, [2], 'tail'])
	}, 3),
	one('map_value', 'map', true, (d) => {
		const m = d.getMap('m')
		insertJSON(d, m, [{ nested: [1, 'two'] }], 'json')
		m.set('any', 'plain')
	}),
	one('map_value_undefined', 'map', false, (d) => {
		insertJSON(d, d.getMap('m'), [undefined], 'undef')
	}),
	// A map entry reads the LAST value of a multi-value item.
	one('map_multi_value', 'map', true, (d) => {
		insertJSON(d, d.getMap('m'), ['first', 2, 'last'], 'multi')
	}),
	// XML attributes are map entries too: ContentJSON, last value wins.
	one('xml_attributes', 'xml', true, (d) => {
		const p = new Y.XmlElement('p')
		d.getXmlFragment('x').insert(0, [p])
		insertJSON(d, p, ['old', 'new'], 'a')
		insertJSON(d, p, ['one'], 'b')
	}),
	// Semantics only: Go sorts object keys and escapes U+2028, and has no
	// undefined (it re-encodes as null), so ygo's bytes differ but must parse
	// to the same values.
	one('array_semantic_only', 'array', false, (d) => {
		insertJSON(d, d.getArray('a'), [{ z: 1, a: 2, m: { y: 1, b: 2 } }, 'line\u2028sep', -0])
	}),
]

const file = path.join(outDir, 'contentjson_yjs_fixtures.json')
// Go has no undefined: ygo surfaces it as nil (as for lib0 Any's undefined
// tag), so expected keeps undefined map values as null instead of dropping them.
const keepUndefined = (k, v) => (v === undefined ? null : v)
fs.writeFileSync(file, JSON.stringify(rows, keepUndefined, 2) + '\n')
console.log(`wrote crdt/testdata/contentjson_yjs_fixtures.json (${rows.length} scenarios)`)
