#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures for YText.applyDelta with embeds.
//
// Each row is a source text mixing runs, formats and embeds. Yjs copies it
// into a fresh doc twice: once via applyDelta(source.toDelta()), once by
// forwarding the observer deltas a peer sees while receiving the source. The
// Go test does the same with the same clientID and must emit the same V1
// bytes, so embeds land at the same index with the same format markers.
//
// A string embed reads back as text, so embeds here are never strings.
// Attribute objects carry one key each: Yjs orders markers by key insertion,
// ygo by sorted key, and one key keeps the bytes comparable. No delta ends in
// '\n', which Yjs's applyDelta would strip.
//
// Regenerated by `make fixtures`; CI's drift gate diffs the result.
const Y = require('yjs')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')
const SOURCE = 7
const COPY = 9

function one (name, build) {
	const src = new Y.Doc()
	src.clientID = SOURCE
	build(src.getText('t'))
	const update = Y.encodeStateAsUpdate(src)

	const copy = new Y.Doc()
	copy.clientID = COPY
	copy.getText('t').applyDelta(src.getText('t').toDelta())

	const peer = new Y.Doc()
	const deltas = []
	peer.getText('t').observe((e) => deltas.push(e.delta))
	Y.applyUpdate(peer, update)
	const fwd = new Y.Doc()
	fwd.clientID = COPY
	for (const d of deltas) fwd.getText('t').applyDelta(d)

	const delta = src.getText('t').toDelta()
	const same = (d) => JSON.stringify(d.getText('t').toDelta()) === JSON.stringify(delta)
	if (!same(copy)) throw new Error(`${name}: yjs copy diverges from the source`)
	// Yjs 13.6's event delta omits an embed in some formatted layouts, so
	// such rows carry no forward bytes; the Go test still checks content.
	return {
		name,
		v1: hex(update),
		delta,
		copyV1: hex(Y.encodeStateAsUpdate(copy)),
		forwardV1: same(fwd) ? hex(Y.encodeStateAsUpdate(fwd)) : null,
	}
}

const rows = [
	one('embeds_between_runs', (t) => {
		t.insert(0, 'ab')
		t.insertEmbed(1, { image: 'x.png' })
		t.insertEmbed(3, [1, 'two'])
		t.insert(4, 'cd')
	}),
	one('formatted_embeds', (t) => {
		t.insert(0, 'hello')
		t.format(0, 2, { bold: true })
		t.insertEmbed(2, { formula: 'e=mc^2' }, { italic: true })
		t.insertEmbed(6, 3.5, { link: 'u' })
	}),
	one('embeds_only', (t) => {
		t.insertEmbed(0, { a: { b: [null, true] } })
		t.insertEmbed(1, 0)
		t.insertEmbed(2, false)
	}),
]

const file = path.join(outDir, 'applydelta_yjs_fixtures.json')
fs.writeFileSync(file, JSON.stringify(rows, null, 2) + '\n')
console.log(`wrote crdt/testdata/applydelta_yjs_fixtures.json (${rows.length} scenarios)`)
