#!/usr/bin/env node
// Deterministic JS→Go conformance fixtures for overwriting a MULTI-VALUE map
// entry or XML attribute.
//
// Setting one key several times in a transaction and then deleting it leaves
// one merged struct for that key. The next writer's origin must be its last
// id: on the first id, a writer whose clientID sorts below the author's lands
// before the old run, and every other peer deletes it as superseded.
//
// Each row records the author's state plus, for a setter below and above the
// author's clientID, Yjs's update and resulting content; the Go test replays
// the set and must emit the same bytes. `split` first applies a write whose
// origin is the run's first id, splitting it; the key must then track the
// run's right half.
//
// Regenerated by `make fixtures`; CI's drift gate diffs the result.
const Y = require('yjs')
const encoding = require('lib0/encoding')
const fs = require('fs')
const path = require('path')

const outDir = path.join(__dirname, '..', 'crdt', 'testdata')
const hex = (u8) => Buffer.from(u8).toString('hex')
const AUTHOR = 10
const SETTERS = [5, 20]
const SPLITTER = 7

const content = (d, kind) =>
	kind === 'map' ? d.getMap('m').toJSON() : d.getXmlFragment('x').toString()

// splitUpdate is a V1 update for one ContentAny value whose origin is the
// author's first id.
function splitUpdate (kind) {
	const e = encoding.createEncoder()
	encoding.writeVarUint(e, 1) // clients
	encoding.writeVarUint(e, 1) // structs
	encoding.writeVarUint(e, SPLITTER)
	encoding.writeVarUint(e, 0) // clock
	encoding.writeUint8(e, 0x80 | 8) // origin, ContentAny
	encoding.writeVarUint(e, AUTHOR)
	encoding.writeVarUint(e, kind === 'map' ? 0 : 1) // the run's first id
	encoding.writeVarUint(e, 1)
	encoding.writeAny(e, kind === 'map' ? 4 : '4')
	encoding.writeVarUint(e, 0) // empty delete set
	return encoding.toUint8Array(e)
}

function setAll (name, kind, gc, base, sv) {
	return SETTERS.map((client) => {
		const s = new Y.Doc({ gc })
		s.clientID = client
		for (const u of base) Y.applyUpdate(s, u)
		if (kind === 'map') s.getMap('m').set('k', 3)
		else s.getXmlFragment('x').get(0).setAttribute('k', '3')
		const update = Y.encodeStateAsUpdate(s, sv)
		const fresh = new Y.Doc()
		Y.applyUpdate(fresh, Y.encodeStateAsUpdate(s))
		const expected = content(fresh, kind)
		if (JSON.stringify(expected) !== JSON.stringify(content(s, kind))) {
			throw new Error(`${name}/${client}: yjs fresh peer diverges from the setter`)
		}
		return { client, update: hex(update), expected }
	})
}

function one (name, kind, gc, n) {
	const d = new Y.Doc({ gc })
	d.clientID = AUTHOR
	if (kind === 'map') {
		const m = d.getMap('m')
		d.transact(() => { for (let i = 1; i <= n; i++) m.set('k', i) })
		m.delete('k')
	} else {
		const x = d.getXmlFragment('x')
		x.insert(0, [new Y.XmlElement('p')])
		const p = x.get(0)
		d.transact(() => { for (let i = 1; i <= n; i++) p.setAttribute('k', String(i)) })
		p.removeAttribute('k')
	}
	const base = Y.encodeStateAsUpdate(d)
	const v2 = Y.encodeStateAsUpdateV2(d)
	const sets = setAll(name, kind, gc, [base], Y.encodeStateVector(d))
	const split = splitUpdate(kind)
	Y.applyUpdate(d, split)
	return {
		name,
		kind,
		gc,
		v1: hex(base),
		v2: hex(v2),
		sets,
		split: { update: hex(split), sets: setAll(name + '/split', kind, gc, [base, split], Y.encodeStateVector(d)) }
	}
}

const rows = []
for (const gc of [true, false]) {
	const tag = gc ? 'gc' : 'nogc'
	rows.push(one(`map_two_values_${tag}`, 'map', gc, 2))
	rows.push(one(`map_three_values_${tag}`, 'map', gc, 3))
	rows.push(one(`xmlattr_two_values_${tag}`, 'xmlattr', gc, 2))
}

const file = path.join(outDir, 'multivalue_yjs_fixtures.json')
fs.writeFileSync(file, JSON.stringify(rows, null, 2) + '\n')
console.log(`wrote crdt/testdata/multivalue_yjs_fixtures.json (${rows.length} scenarios)`)
